### ISSUE TITLE
PPD file uploading

### ISSUE THREAD

**Issue by edyapups** [ctalkington/python-ipp#210]
Hi, I ran into the need to load PPD files in the [CUPS-Add-Modify-Class](https://opensource.apple.com/source/cups/cups-218/cups/doc/help/spec-ipp.html#CUPS_ADD_MODIFY_CLASS) method, but I did not find the required capability in the code. Maybe you can suggest how to do this?

**Comment by ctalkington** [comment]
outside of scope of this package currently. closing due to age.
