### ISSUE TITLE
Any chance of supporting IPP DEFAULT_PROTO_VERSION 1,1?

### ISSUE THREAD

**Issue by datdamnzotz** [ctalkington/python-ipp#221]
I have a couple of older LaserJets 	
Color LaserJet 4700, and LaserJet 5200 I'd love to talk to.

Changing the default protocol version to 1.1 I get:
`Printer(info=Info(name='HPLJ4700C', printer_name='HPLJ4700C', printer_uri_supported=['ipp://192.168.1.82/ipp/port1', 'ipp://192.168.1.82/ipp'], uptime=241843, command_set=None, location='', manufacturer='Unknown', model='Unknown', printer_info='MFG:Hewlett-Packard;CMD:PJL,MLC,BIDI-ECP,PCLXL,PCL,PDF,PJL,POSTSCRIPT;1284.4DL:4d,4e,1;MDL:HP Color LaserJet 4700;CLS:PRINTER;D', serial=None, uuid=None, version=None), markers=[], state=State(printer_state='idle', reasons=None, message=None), uris=[Uri(uri='ipp://192.168.1.82/ipp/port1', authentication='requesting-user-name', security=None), Uri(uri='ipp://192.168.1.82/ipp', authentication='requesting-user-name', security=None)])`

I'm after ink levels etc... but I'm not seeing them. (maybe not there?)

**Comment by ctalkington** [comment]
sorry for long delay. I would need a debug dump most likely. v0.18.0 (released today) did improve some handling if you only have single ink like black.
